### ISSUE TITLE
Error in unit tests run

### ISSUE THREAD

**Issue by tvkent** [23andMe/phasedibd#1]
Hi, 

I got the following error when running the tests after installation. Not sure if this is on my end or an error in the tests script.

======================================================================
ERROR: test_PBWT_default_haplotypes (__main__.TestPbwtBasics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit_tests.py", line 32, in test_PBWT_default_haplotypes
    self.assertTrue(np.all(ibd_segs.eq(true_segs)))
  File "/ohta/tyler.kent/Software/anaconda3/lib/python3.5/unittest/case.py", line 675, in assertTrue
    if not expr:
  File "/ohta/tyler.kent/Software/anaconda3/lib/python3.5/site-packages/pandas/core/generic.py", line 892, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by tvkent** [comment]
Pull request #2 should fix this.

**Comment by wf8** [comment]
Thanks @tvkent but pull request #2 causes the tests to now fail in python 3.7 and 3.8. What version of pandas/numpy were you using when this test failed for you?
